"use client";

import { useQuery } from "@tanstack/react-query";
import { LogOut, UserRound } from "lucide-react";
import { useRouter } from "next/navigation";
import { AppShell } from "@/components/layout/app-shell";
import { EmptyState } from "@/components/ui/empty-state";
import { LoadingBlock } from "@/components/ui/loading";
import { PublicationCard } from "@/components/feed/publication-card";
import { clientApi } from "@/lib/client-api";
import type { Comment, CursorPage, Publication, User } from "@/lib/types";
import { useAuth } from "@/providers/auth-provider";

export default function ProfilePage(){const router=useRouter();const {user,loading,logout}=useAuth();const publicProfile=useQuery({queryKey:["profile",user?.id],queryFn:()=>clientApi<User>(`/users/${user!.id}/`),enabled:Boolean(user)});const publications=useQuery({queryKey:["profile-publications",user?.id],queryFn:()=>clientApi<CursorPage<Publication>>(`/publications/?author=${user!.id}`),enabled:Boolean(user)});const answers=useQuery({queryKey:["profile-answers",user?.id],queryFn:()=>clientApi<CursorPage<Comment>>(`/users/${user!.id}/answers/`),enabled:Boolean(user)});if(loading)return <AppShell><LoadingBlock/></AppShell>;if(!user)return <AppShell><EmptyState icon={UserRound} title="Профиль доступен после входа" text="Зарегистрируйтесь, чтобы создать социальный профиль Night Iris." action={{href:"/register",label:"Создать аккаунт"}}/></AppShell>;const profile=publicProfile.data??user;async function signOut(){await logout();router.push("/");}
return <AppShell><section className="profile-shell"><div className="profile-banner"><div className="profile-rings"/></div><div className="profile-main"><div className="avatar avatar-xl">{user.nickname.slice(0,2).toUpperCase()}</div><div className="profile-copy"><div className="profile-title-row"><div><h1>{[user.first_name,user.last_name].filter(Boolean).join(" ")||user.nickname}</h1><span>@{user.nickname}</span></div><button className="secondary-button" onClick={signOut}><LogOut size={14}/> Выйти</button></div><p>{user.bio||"Описание профиля пока не заполнено."}</p><div className="profile-meta">{profile.follower_count??0} подписчиков · {profile.following_count??0} подписок · с {new Date(user.date_joined).toLocaleDateString("ru-RU")}</div></div></div></section><div className="profile-stats"><div className="stat-box"><strong>{publications.data?.results.length??0}</strong><span>публикаций на странице</span></div><div className="stat-box"><strong>{answers.data?.results.length??0}</strong><span>ответов на странице</span></div><div className="stat-box"><strong>{user.country}</strong><span>страна</span></div></div><section className="section-block"><div className="section-heading"><h2>Публикации</h2></div>{publications.isLoading?<LoadingBlock/>:publications.data?.results.length?<div className="feed-list">{publications.data.results.map(p=><PublicationCard key={p.id} publication={p}/>)}</div>:<div className="inline-empty">Вы ещё ничего не публиковали.</div>}</section></AppShell>}
