"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Search, ShieldCheck, ShieldOff, UserCheck, UserX } from "lucide-react";
import { useState } from "react";
import { AdminEmpty, StatusBadge } from "@/components/admin/admin-ui";
import { LoadingBlock } from "@/components/ui/loading";
import { clientApi, errorMessage } from "@/lib/client-api";
import type { AdminPage, AdminUser } from "@/lib/types";
import { useAuth } from "@/providers/auth-provider";

export default function AdminUsersPage(){ const [search,setSearch]=useState(""); const [status,setStatus]=useState(""); const qc=useQueryClient(); const {user:me}=useAuth();
 const q=useQuery({queryKey:["admin","users",search,status],queryFn:()=>clientApi<AdminPage<AdminUser>>(`/admin/users/?limit=100&q=${encodeURIComponent(search)}&status=${status}`)});
 const mutate=useMutation({mutationFn:({id,payload}:{id:string;payload:Record<string,boolean>})=>clientApi<AdminUser>(`/admin/users/${id}/`,{method:"PATCH",body:JSON.stringify(payload)}),onSuccess:()=>{qc.invalidateQueries({queryKey:["admin","users"]});qc.invalidateQueries({queryKey:["admin","overview"]});}});
 return <><div className="admin-page-head"><div><div className="eyebrow">ДОСТУП И УЧЁТНЫЕ ЗАПИСИ</div><h1>Пользователи</h1><p>Поиск, блокировка доступа и управление ролью сотрудника. Superuser-права через эту панель не выдаются.</p></div></div><div className="admin-toolbar"><div className="admin-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ник, email, имя…"/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Все статусы</option><option value="active">Активные</option><option value="inactive">Отключённые</option></select></div>
 {q.isLoading?<LoadingBlock/>:q.error?<div className="error-panel">{errorMessage(q.error)}</div>:q.data!.results.length===0?<AdminEmpty title="Пользователей не найдено" text="Измените фильтры или дождитесь первых регистраций."/>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Пользователь</th><th>Статус</th><th>Контент</th><th>Регистрация</th><th>Действия</th></tr></thead><tbody>{q.data!.results.map(u=><tr key={u.id}><td><div className="admin-user-cell"><span className="avatar avatar-sm">{u.nickname.slice(0,2).toUpperCase()}</span><div><strong>@{u.nickname}</strong><span>{u.email}</span></div></div></td><td><div className="admin-badge-stack"><StatusBadge value={u.is_active?"active":"inactive"}/>{u.is_superuser?<span className="role-badge">SUPERUSER</span>:u.is_staff?<span className="role-badge">STAFF</span>:null}</div></td><td><strong>{u.publication_count}</strong> публикаций<br/><span className="muted-cell">{u.comment_count} ответов</span></td><td>{new Date(u.date_joined).toLocaleDateString("ru-RU")}</td><td><div className="admin-row-actions"><button disabled={mutate.isPending||u.id===me?.id} title={u.is_active?"Отключить":"Включить"} onClick={()=>mutate.mutate({id:u.id,payload:{is_active:!u.is_active}})}>{u.is_active?<UserX size={16}/>:<UserCheck size={16}/>}</button>{me?.is_superuser&&!u.is_superuser?<button disabled={mutate.isPending||u.id===me?.id} title={u.is_staff?"Снять staff":"Выдать staff"} onClick={()=>mutate.mutate({id:u.id,payload:{is_staff:!u.is_staff}})}>{u.is_staff?<ShieldOff size={16}/>:<ShieldCheck size={16}/>}</button>:null}</div></td></tr>)}</tbody></table></div>}
 {mutate.error?<div className="form-error admin-inline-error">{errorMessage(mutate.error)}</div>:null}</> }
