--
-- PostgreSQL database dump
--

\restrict 5FqoMa3iFoTGx20PDSvNKg3vfdL0FmULgyPAGcwGMjiSvfWOGE6QuR3mOmVPEXu

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg13+1)
-- Dumped by pg_dump version 18.4 (Debian 18.4-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: forum
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO forum;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: forum
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: forum
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO forum;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: forum
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: forum
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO forum;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: forum
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: communities_community; Type: TABLE; Schema: public; Owner: forum
--

CREATE TABLE public.communities_community (
    id bigint NOT NULL,
    public_id uuid NOT NULL,
    slug character varying(80) NOT NULL,
    name character varying(120) NOT NULL,
    description text NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    owner_id bigint NOT NULL
);


ALTER TABLE public.communities_community OWNER TO forum;

--
-- Name: communities_community_id_seq; Type: SEQUENCE; Schema: public; Owner: forum
--

ALTER TABLE public.communities_community ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.communities_community_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: forum
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO forum;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: forum
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: forum
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO forum;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: forum
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: forum
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO forum;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: forum
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: forum
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO forum;

--
-- Name: media_mediaasset; Type: TABLE; Schema: public; Owner: forum
--

CREATE TABLE public.media_mediaasset (
    id bigint NOT NULL,
    public_id uuid NOT NULL,
    object_key character varying(500) NOT NULL,
    original_name character varying(255) NOT NULL,
    declared_content_type character varying(255) NOT NULL,
    kind character varying(16) NOT NULL,
    size_bytes bigint NOT NULL,
    multipart_upload_id text NOT NULL,
    part_size bigint NOT NULL,
    part_count integer NOT NULL,
    status character varying(32) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    owner_id bigint NOT NULL,
    CONSTRAINT media_mediaasset_part_count_check CHECK ((part_count >= 0)),
    CONSTRAINT media_mediaasset_part_size_check CHECK ((part_size >= 0)),
    CONSTRAINT media_mediaasset_size_bytes_check CHECK ((size_bytes >= 0))
);


ALTER TABLE public.media_mediaasset OWNER TO forum;

--
-- Name: media_mediaasset_id_seq; Type: SEQUENCE; Schema: public; Owner: forum
--

ALTER TABLE public.media_mediaasset ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_mediaasset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: media_publicationmedia; Type: TABLE; Schema: public; Owner: forum
--

CREATE TABLE public.media_publicationmedia (
    id bigint NOT NULL,
    role character varying(32) NOT NULL,
    sort_order integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    asset_id bigint NOT NULL,
    publication_id bigint NOT NULL,
    CONSTRAINT media_publicationmedia_sort_order_check CHECK ((sort_order >= 0))
);


ALTER TABLE public.media_publicationmedia OWNER TO forum;

--
-- Name: media_publicationmedia_id_seq; Type: SEQUENCE; Schema: public; Owner: forum
--

ALTER TABLE public.media_publicationmedia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_publicationmedia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: publications_publication; Type: TABLE; Schema: public; Owner: forum
--

CREATE TABLE public.publications_publication (
    id bigint NOT NULL,
    public_id uuid NOT NULL,
    kind character varying(16) NOT NULL,
    title character varying(300) NOT NULL,
    content jsonb NOT NULL,
    content_text text NOT NULL,
    visibility character varying(16) NOT NULL,
    current_revision integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    author_id bigint NOT NULL,
    community_id bigint,
    CONSTRAINT publications_publication_current_revision_check CHECK ((current_revision >= 0))
);


ALTER TABLE public.publications_publication OWNER TO forum;

--
-- Name: publications_publication_id_seq; Type: SEQUENCE; Schema: public; Owner: forum
--

ALTER TABLE public.publications_publication ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.publications_publication_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: publications_publication_tags; Type: TABLE; Schema: public; Owner: forum
--

CREATE TABLE public.publications_publication_tags (
    id bigint NOT NULL,
    publication_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


ALTER TABLE public.publications_publication_tags OWNER TO forum;

--
-- Name: publications_publication_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: forum
--

ALTER TABLE public.publications_publication_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.publications_publication_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: publications_publicationrevision; Type: TABLE; Schema: public; Owner: forum
--

CREATE TABLE public.publications_publicationrevision (
    id bigint NOT NULL,
    revision_number integer NOT NULL,
    title character varying(300) NOT NULL,
    content jsonb NOT NULL,
    tags_snapshot jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    editor_id bigint NOT NULL,
    publication_id bigint NOT NULL,
    media_snapshot jsonb NOT NULL,
    CONSTRAINT publications_publicationrevision_revision_number_check CHECK ((revision_number >= 0))
);


ALTER TABLE public.publications_publicationrevision OWNER TO forum;

--
-- Name: publications_publicationrevision_id_seq; Type: SEQUENCE; Schema: public; Owner: forum
--

ALTER TABLE public.publications_publicationrevision ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.publications_publicationrevision_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: publications_tag; Type: TABLE; Schema: public; Owner: forum
--

CREATE TABLE public.publications_tag (
    id bigint NOT NULL,
    public_id uuid NOT NULL,
    name character varying(80) NOT NULL,
    slug character varying(80) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.publications_tag OWNER TO forum;

--
-- Name: publications_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: forum
--

ALTER TABLE public.publications_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.publications_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: social_communitysubscription; Type: TABLE; Schema: public; Owner: forum
--

CREATE TABLE public.social_communitysubscription (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    community_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.social_communitysubscription OWNER TO forum;

--
-- Name: social_communitysubscription_id_seq; Type: SEQUENCE; Schema: public; Owner: forum
--

ALTER TABLE public.social_communitysubscription ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.social_communitysubscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: social_userfollow; Type: TABLE; Schema: public; Owner: forum
--

CREATE TABLE public.social_userfollow (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    follower_id bigint NOT NULL,
    following_id bigint NOT NULL,
    CONSTRAINT social_user_cannot_follow_self CHECK ((NOT (follower_id = following_id)))
);


ALTER TABLE public.social_userfollow OWNER TO forum;

--
-- Name: social_userfollow_id_seq; Type: SEQUENCE; Schema: public; Owner: forum
--

ALTER TABLE public.social_userfollow ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.social_userfollow_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: forum
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO forum;

--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: forum
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: forum
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id bigint,
    jti character varying(255) CONSTRAINT token_blacklist_outstandingtoken_jti_hex_not_null NOT NULL
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO forum;

--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: forum
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user; Type: TABLE; Schema: public; Owner: forum
--

CREATE TABLE public.users_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    public_id uuid NOT NULL,
    nickname character varying(32) NOT NULL,
    email character varying(254) NOT NULL,
    country character varying(2) NOT NULL,
    nationality character varying(2) NOT NULL,
    interface_language character varying(10) NOT NULL,
    bio text NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.users_user OWNER TO forum;

--
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: forum
--

CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_user_groups OWNER TO forum;

--
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: forum
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: forum
--

ALTER TABLE public.users_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: forum
--

CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_user_permissions OWNER TO forum;

--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: forum
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: forum
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: forum
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: forum
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add Blacklisted Token	7	add_blacklistedtoken
26	Can change Blacklisted Token	7	change_blacklistedtoken
27	Can delete Blacklisted Token	7	delete_blacklistedtoken
28	Can view Blacklisted Token	7	view_blacklistedtoken
29	Can add Outstanding Token	8	add_outstandingtoken
30	Can change Outstanding Token	8	change_outstandingtoken
31	Can delete Outstanding Token	8	delete_outstandingtoken
32	Can view Outstanding Token	8	view_outstandingtoken
33	Can add community	9	add_community
34	Can change community	9	change_community
35	Can delete community	9	delete_community
36	Can view community	9	view_community
37	Can add community subscription	10	add_communitysubscription
38	Can change community subscription	10	change_communitysubscription
39	Can delete community subscription	10	delete_communitysubscription
40	Can view community subscription	10	view_communitysubscription
41	Can add user follow	11	add_userfollow
42	Can change user follow	11	change_userfollow
43	Can delete user follow	11	delete_userfollow
44	Can view user follow	11	view_userfollow
45	Can add tag	12	add_tag
46	Can change tag	12	change_tag
47	Can delete tag	12	delete_tag
48	Can view tag	12	view_tag
49	Can add publication	13	add_publication
50	Can change publication	13	change_publication
51	Can delete publication	13	delete_publication
52	Can view publication	13	view_publication
53	Can add publication revision	14	add_publicationrevision
54	Can change publication revision	14	change_publicationrevision
55	Can delete publication revision	14	delete_publicationrevision
56	Can view publication revision	14	view_publicationrevision
57	Can add media asset	15	add_mediaasset
58	Can change media asset	15	change_mediaasset
59	Can delete media asset	15	delete_mediaasset
60	Can view media asset	15	view_mediaasset
61	Can add publication media	16	add_publicationmedia
62	Can change publication media	16	change_publicationmedia
63	Can delete publication media	16	delete_publicationmedia
64	Can view publication media	16	view_publicationmedia
\.


--
-- Data for Name: communities_community; Type: TABLE DATA; Schema: public; Owner: forum
--

COPY public.communities_community (id, public_id, slug, name, description, is_active, created_at, updated_at, owner_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: forum
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: forum
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	users	user
7	token_blacklist	blacklistedtoken
8	token_blacklist	outstandingtoken
9	communities	community
10	social	communitysubscription
11	social	userfollow
12	publications	tag
13	publications	publication
14	publications	publicationrevision
15	media	mediaasset
16	media	publicationmedia
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: forum
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-08-07 07:00:08.967886+00
2	contenttypes	0002_remove_content_type_name	2026-08-07 07:00:08.969512+00
3	auth	0001_initial	2026-08-07 07:00:08.975099+00
4	auth	0002_alter_permission_name_max_length	2026-08-07 07:00:08.976296+00
5	auth	0003_alter_user_email_max_length	2026-08-07 07:00:08.977414+00
6	auth	0004_alter_user_username_opts	2026-08-07 07:00:08.978724+00
7	auth	0005_alter_user_last_login_null	2026-08-07 07:00:08.979844+00
8	auth	0006_require_contenttypes_0002	2026-08-07 07:00:08.980131+00
9	auth	0007_alter_validators_add_error_messages	2026-08-07 07:00:08.981395+00
10	auth	0008_alter_user_username_max_length	2026-08-07 07:00:08.982463+00
11	auth	0009_alter_user_last_name_max_length	2026-08-07 07:00:08.985359+00
12	auth	0010_alter_group_name_max_length	2026-08-07 07:00:08.986675+00
13	auth	0011_update_proxy_permissions	2026-08-07 07:00:08.987681+00
14	auth	0012_alter_user_first_name_max_length	2026-08-07 07:00:08.988724+00
15	users	0001_initial	2026-08-07 07:00:08.994767+00
16	admin	0001_initial	2026-08-07 07:00:08.999203+00
17	admin	0002_logentry_remove_auto_add	2026-08-07 07:00:09.00328+00
18	admin	0003_logentry_add_action_flag_choices	2026-08-07 07:00:09.005746+00
19	sessions	0001_initial	2026-08-07 07:00:09.00763+00
20	token_blacklist	0001_initial	2026-08-07 07:30:34.218598+00
21	token_blacklist	0002_outstandingtoken_jti_hex	2026-08-07 07:30:34.221244+00
22	token_blacklist	0003_auto_20171017_2007	2026-08-07 07:30:34.224324+00
23	token_blacklist	0004_auto_20171017_2013	2026-08-07 07:30:34.226806+00
24	token_blacklist	0005_remove_outstandingtoken_jti	2026-08-07 07:30:34.229099+00
25	token_blacklist	0006_auto_20171017_2113	2026-08-07 07:30:34.231494+00
26	token_blacklist	0007_auto_20171017_2214	2026-08-07 07:30:34.237452+00
27	token_blacklist	0008_migrate_to_bigautofield	2026-08-07 07:30:34.244666+00
28	token_blacklist	0010_fix_migrate_to_bigautofield	2026-08-07 07:30:34.248236+00
29	token_blacklist	0011_linearizes_history	2026-08-07 07:30:34.248604+00
30	token_blacklist	0012_alter_outstandingtoken_user	2026-08-07 07:30:34.250699+00
31	token_blacklist	0013_alter_blacklistedtoken_options_and_more	2026-08-07 07:30:34.253731+00
32	users	0002_user_users_email_case_insensitive_unique	2026-08-07 07:30:34.258444+00
33	communities	0001_initial	2026-08-07 12:09:02.966786+00
34	social	0001_initial	2026-08-07 12:09:02.975602+00
35	publications	0001_initial	2026-08-10 10:40:51.733986+00
36	media	0001_initial	2026-08-13 05:02:00.402436+00
37	publications	0002_publicationrevision_media_snapshot	2026-08-13 05:10:37.08257+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: forum
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: media_mediaasset; Type: TABLE DATA; Schema: public; Owner: forum
--

COPY public.media_mediaasset (id, public_id, object_key, original_name, declared_content_type, kind, size_bytes, multipart_upload_id, part_size, part_count, status, created_at, completed_at, owner_id) FROM stdin;
\.


--
-- Data for Name: media_publicationmedia; Type: TABLE DATA; Schema: public; Owner: forum
--

COPY public.media_publicationmedia (id, role, sort_order, created_at, asset_id, publication_id) FROM stdin;
\.


--
-- Data for Name: publications_publication; Type: TABLE DATA; Schema: public; Owner: forum
--

COPY public.publications_publication (id, public_id, kind, title, content, content_text, visibility, current_revision, created_at, updated_at, author_id, community_id) FROM stdin;
1	6eb481ab-b8a8-4392-bc97-ff1ef22d1231	topic	Стоит ли использовать Django для большого форума?	[{"text": "Хочу обсудить архитектуру очень большого форума.", "type": "paragraph"}]	Хочу обсудить архитектуру очень большого форума.	published	2	2026-08-11 07:09:44.348831+00	2026-08-11 07:13:33.406925+00	1	\N
\.


--
-- Data for Name: publications_publication_tags; Type: TABLE DATA; Schema: public; Owner: forum
--

COPY public.publications_publication_tags (id, publication_id, tag_id) FROM stdin;
1	1	1
2	1	2
3	1	3
\.


--
-- Data for Name: publications_publicationrevision; Type: TABLE DATA; Schema: public; Owner: forum
--

COPY public.publications_publicationrevision (id, revision_number, title, content, tags_snapshot, created_at, editor_id, publication_id, media_snapshot) FROM stdin;
1	1	Стоит ли использовать Django для большого форума?	[{"text": "Хочу обсудить архитектуру большого форума.", "type": "paragraph"}, {"text": "Основной вопрос", "type": "heading", "level": 2}, {"text": "Насколько далеко можно масштабировать Django и PostgreSQL?", "type": "paragraph"}]	[{"name": "API", "slug": "api"}, {"name": "Django", "slug": "django"}, {"name": "PostgreSQL", "slug": "postgresql"}]	2026-08-11 07:09:44.360329+00	1	1	[]
2	2	Стоит ли использовать Django для большого форума?	[{"text": "Хочу обсудить архитектуру очень большого форума.", "type": "paragraph"}]	[{"name": "API", "slug": "api"}, {"name": "Django", "slug": "django"}, {"name": "PostgreSQL", "slug": "postgresql"}]	2026-08-11 07:13:33.409064+00	1	1	[]
\.


--
-- Data for Name: publications_tag; Type: TABLE DATA; Schema: public; Owner: forum
--

COPY public.publications_tag (id, public_id, name, slug, created_at) FROM stdin;
1	07114c6f-9419-4a64-9e43-80d875e5bac4	Django	django	2026-08-11 07:09:44.352326+00
2	50e4a35b-85c1-4af9-ae32-300e925b43d4	PostgreSQL	postgresql	2026-08-11 07:09:44.354174+00
3	7a559383-a9f7-48f8-bbfc-1d30f90fbb4b	API	api	2026-08-11 07:09:44.355246+00
\.


--
-- Data for Name: social_communitysubscription; Type: TABLE DATA; Schema: public; Owner: forum
--

COPY public.social_communitysubscription (id, created_at, community_id, user_id) FROM stdin;
\.


--
-- Data for Name: social_userfollow; Type: TABLE DATA; Schema: public; Owner: forum
--

COPY public.social_userfollow (id, created_at, follower_id, following_id) FROM stdin;
\.


--
-- Data for Name: token_blacklist_blacklistedtoken; Type: TABLE DATA; Schema: public; Owner: forum
--

COPY public.token_blacklist_blacklistedtoken (id, blacklisted_at, token_id) FROM stdin;
\.


--
-- Data for Name: token_blacklist_outstandingtoken; Type: TABLE DATA; Schema: public; Owner: forum
--

COPY public.token_blacklist_outstandingtoken (id, token, created_at, expires_at, user_id, jti) FROM stdin;
1	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4ODY3OTg3MCwiaWF0IjoxNzg2MDg3ODcwLCJqdGkiOiJiMDFjNWM1YTllNTU0NGQ5YWNhZDExNzVmMzIzNGUyNCIsInVzZXJfaWQiOiI5YzM2NDFmNC04NTY1LTQ1ZDAtODI5MS03NTUzMDc4MmNkMmEifQ.Iph5XhNDjWsqPV_acktk-77mygApzAK4PfBHOX9RXqU	2026-08-07 07:31:10.56313+00	2026-09-06 07:31:10+00	1	b01c5c5a9e5544d9acad1175f3234e24
2	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4ODY3OTkwNiwiaWF0IjoxNzg2MDg3OTA2LCJqdGkiOiJiZGM5YmMyN2M3OGY0MjNiOTJjMmU3NWE5NDNiZDg3MCIsInVzZXJfaWQiOiI5YzM2NDFmNC04NTY1LTQ1ZDAtODI5MS03NTUzMDc4MmNkMmEifQ.U1xgEzhiGys0qX8VbhuwCKcN1dhwSnoVPuosd5AZhAA	2026-08-07 07:31:46.380581+00	2026-09-06 07:31:46+00	1	bdc9bc27c78f423b92c2e75a943bd870
3	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4OTAyMjY5NCwiaWF0IjoxNzg2NDMwNjk0LCJqdGkiOiJiNGI0ZTBlOGU1ZTk0ODE5ODAyZjM0YzE0ZTFjZmZkNyIsInVzZXJfaWQiOiI5YzM2NDFmNC04NTY1LTQ1ZDAtODI5MS03NTUzMDc4MmNkMmEifQ.M4R8N0a7jTWyOvV7T7BpR8NeoU6Rkzhr-yvt6exzFuM	2026-08-11 06:44:54.313009+00	2026-09-10 06:44:54+00	1	b4b4e0e8e5e94819802f34c14e1cffd7
4	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4OTAyMzgzOCwiaWF0IjoxNzg2NDMxODM4LCJqdGkiOiI0MDdjMThkZWMyMGY0OWQ0YWYyYzFmYjkyNWVhMzY2YyIsInVzZXJfaWQiOiI5YzM2NDFmNC04NTY1LTQ1ZDAtODI5MS03NTUzMDc4MmNkMmEifQ.z_nuvIyTFYHqAbrrw4jFqkkEhnS-Aka4KrCYBDbRsTY	2026-08-11 07:03:58.111644+00	2026-09-10 07:03:58+00	1	407c18dec20f49d4af2c1fb925ea366c
5	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4OTAyNDA1MiwiaWF0IjoxNzg2NDMyMDUyLCJqdGkiOiIxMWIwYTA5ZjJlZTc0NGJjYmRkYTEwN2MxZGMyNTYyMCIsInVzZXJfaWQiOiI5YzM2NDFmNC04NTY1LTQ1ZDAtODI5MS03NTUzMDc4MmNkMmEifQ.z3tvDuf25Sb1NIxRO8-aL11B_QMPR9QBl3-M-nrSe_g	2026-08-11 07:07:32.831146+00	2026-09-10 07:07:32+00	1	11b0a09f2ee744bcbdda107c1dc25620
6	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4OTAyNDMwMiwiaWF0IjoxNzg2NDMyMzAyLCJqdGkiOiI3M2IzMGMzYzgyMTI0NWI2OGZiN2E1MGYzN2JmNTU2NiIsInVzZXJfaWQiOiI5YzM2NDFmNC04NTY1LTQ1ZDAtODI5MS03NTUzMDc4MmNkMmEifQ.YrvLGXM2jRjpxe8eLmzZkRQfv_ENcXkkSyGnPC8zpmM	2026-08-11 07:11:42.561296+00	2026-09-10 07:11:42+00	1	73b30c3c821245b68fb7a50f37bf5566
\.


--
-- Data for Name: users_user; Type: TABLE DATA; Schema: public; Owner: forum
--

COPY public.users_user (id, password, last_login, is_superuser, first_name, last_name, is_staff, is_active, date_joined, public_id, nickname, email, country, nationality, interface_language, bio, updated_at) FROM stdin;
1	pbkdf2_sha256$1000000$pTEiuFwkpDNwRyTebNiBC7$txFFsfVWMVeB7h4ccRIoWJvRtsfIWSX+PmtGj5E7itU=	\N	f	Emil	Test	f	t	2026-08-07 07:31:10.442645+00	9c3641f4-8565-45d0-8291-75530782cd2a	Emil	emil@example.com	RU	RU	ru		2026-08-07 07:31:10.560547+00
\.


--
-- Data for Name: users_user_groups; Type: TABLE DATA; Schema: public; Owner: forum
--

COPY public.users_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: forum
--

COPY public.users_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: forum
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: forum
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: forum
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 64, true);


--
-- Name: communities_community_id_seq; Type: SEQUENCE SET; Schema: public; Owner: forum
--

SELECT pg_catalog.setval('public.communities_community_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: forum
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: forum
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 16, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: forum
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 37, true);


--
-- Name: media_mediaasset_id_seq; Type: SEQUENCE SET; Schema: public; Owner: forum
--

SELECT pg_catalog.setval('public.media_mediaasset_id_seq', 1, false);


--
-- Name: media_publicationmedia_id_seq; Type: SEQUENCE SET; Schema: public; Owner: forum
--

SELECT pg_catalog.setval('public.media_publicationmedia_id_seq', 1, false);


--
-- Name: publications_publication_id_seq; Type: SEQUENCE SET; Schema: public; Owner: forum
--

SELECT pg_catalog.setval('public.publications_publication_id_seq', 1, true);


--
-- Name: publications_publication_tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: forum
--

SELECT pg_catalog.setval('public.publications_publication_tags_id_seq', 3, true);


--
-- Name: publications_publicationrevision_id_seq; Type: SEQUENCE SET; Schema: public; Owner: forum
--

SELECT pg_catalog.setval('public.publications_publicationrevision_id_seq', 2, true);


--
-- Name: publications_tag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: forum
--

SELECT pg_catalog.setval('public.publications_tag_id_seq', 3, true);


--
-- Name: social_communitysubscription_id_seq; Type: SEQUENCE SET; Schema: public; Owner: forum
--

SELECT pg_catalog.setval('public.social_communitysubscription_id_seq', 1, false);


--
-- Name: social_userfollow_id_seq; Type: SEQUENCE SET; Schema: public; Owner: forum
--

SELECT pg_catalog.setval('public.social_userfollow_id_seq', 1, false);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: forum
--

SELECT pg_catalog.setval('public.token_blacklist_blacklistedtoken_id_seq', 1, false);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: forum
--

SELECT pg_catalog.setval('public.token_blacklist_outstandingtoken_id_seq', 6, true);


--
-- Name: users_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: forum
--

SELECT pg_catalog.setval('public.users_user_groups_id_seq', 1, false);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: forum
--

SELECT pg_catalog.setval('public.users_user_id_seq', 1, true);


--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: forum
--

SELECT pg_catalog.setval('public.users_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: communities_community communities_community_pkey; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.communities_community
    ADD CONSTRAINT communities_community_pkey PRIMARY KEY (id);


--
-- Name: communities_community communities_community_public_id_key; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.communities_community
    ADD CONSTRAINT communities_community_public_id_key UNIQUE (public_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: media_mediaasset media_mediaasset_object_key_key; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.media_mediaasset
    ADD CONSTRAINT media_mediaasset_object_key_key UNIQUE (object_key);


--
-- Name: media_mediaasset media_mediaasset_pkey; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.media_mediaasset
    ADD CONSTRAINT media_mediaasset_pkey PRIMARY KEY (id);


--
-- Name: media_mediaasset media_mediaasset_public_id_key; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.media_mediaasset
    ADD CONSTRAINT media_mediaasset_public_id_key UNIQUE (public_id);


--
-- Name: media_publicationmedia media_publicationmedia_pkey; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.media_publicationmedia
    ADD CONSTRAINT media_publicationmedia_pkey PRIMARY KEY (id);


--
-- Name: media_publicationmedia media_unique_publication_asset_role; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.media_publicationmedia
    ADD CONSTRAINT media_unique_publication_asset_role UNIQUE (publication_id, asset_id, role);


--
-- Name: publications_publicationrevision publication_unique_revision; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.publications_publicationrevision
    ADD CONSTRAINT publication_unique_revision UNIQUE (publication_id, revision_number);


--
-- Name: publications_publication publications_publication_pkey; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.publications_publication
    ADD CONSTRAINT publications_publication_pkey PRIMARY KEY (id);


--
-- Name: publications_publication publications_publication_public_id_key; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.publications_publication
    ADD CONSTRAINT publications_publication_public_id_key UNIQUE (public_id);


--
-- Name: publications_publication_tags publications_publication_publication_id_tag_id_f614200d_uniq; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.publications_publication_tags
    ADD CONSTRAINT publications_publication_publication_id_tag_id_f614200d_uniq UNIQUE (publication_id, tag_id);


--
-- Name: publications_publication_tags publications_publication_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.publications_publication_tags
    ADD CONSTRAINT publications_publication_tags_pkey PRIMARY KEY (id);


--
-- Name: publications_publicationrevision publications_publicationrevision_pkey; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.publications_publicationrevision
    ADD CONSTRAINT publications_publicationrevision_pkey PRIMARY KEY (id);


--
-- Name: publications_tag publications_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.publications_tag
    ADD CONSTRAINT publications_tag_pkey PRIMARY KEY (id);


--
-- Name: publications_tag publications_tag_public_id_key; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.publications_tag
    ADD CONSTRAINT publications_tag_public_id_key UNIQUE (public_id);


--
-- Name: social_communitysubscription social_communitysubscription_pkey; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.social_communitysubscription
    ADD CONSTRAINT social_communitysubscription_pkey PRIMARY KEY (id);


--
-- Name: social_communitysubscription social_unique_community_subscription; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.social_communitysubscription
    ADD CONSTRAINT social_unique_community_subscription UNIQUE (user_id, community_id);


--
-- Name: social_userfollow social_unique_user_follow; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.social_userfollow
    ADD CONSTRAINT social_unique_user_follow UNIQUE (follower_id, following_id);


--
-- Name: social_userfollow social_userfollow_pkey; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.social_userfollow
    ADD CONSTRAINT social_userfollow_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: users_user users_user_email_key; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_email_key UNIQUE (email);


--
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- Name: users_user users_user_nickname_key; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_nickname_key UNIQUE (nickname);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- Name: users_user users_user_public_id_key; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_public_id_key UNIQUE (public_id);


--
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: communities_community_owner_id_15a7d936; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX communities_community_owner_id_15a7d936 ON public.communities_community USING btree (owner_id);


--
-- Name: communities_community_slug_121bd9e8; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX communities_community_slug_121bd9e8 ON public.communities_community USING btree (slug);


--
-- Name: communities_community_slug_121bd9e8_like; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX communities_community_slug_121bd9e8_like ON public.communities_community USING btree (slug varchar_pattern_ops);


--
-- Name: communities_slug_case_insensitive_unique; Type: INDEX; Schema: public; Owner: forum
--

CREATE UNIQUE INDEX communities_slug_case_insensitive_unique ON public.communities_community USING btree (lower((slug)::text));


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: media_media_owner_i_f6f032_idx; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX media_media_owner_i_f6f032_idx ON public.media_mediaasset USING btree (owner_id, status, created_at DESC);


--
-- Name: media_mediaasset_object_key_b35287f5_like; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX media_mediaasset_object_key_b35287f5_like ON public.media_mediaasset USING btree (object_key varchar_pattern_ops);


--
-- Name: media_mediaasset_owner_id_bb8ce699; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX media_mediaasset_owner_id_bb8ce699 ON public.media_mediaasset USING btree (owner_id);


--
-- Name: media_one_preview_video; Type: INDEX; Schema: public; Owner: forum
--

CREATE UNIQUE INDEX media_one_preview_video ON public.media_publicationmedia USING btree (publication_id) WHERE ((role)::text = 'preview_video'::text);


--
-- Name: media_publi_publica_5550ac_idx; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX media_publi_publica_5550ac_idx ON public.media_publicationmedia USING btree (publication_id, role, sort_order);


--
-- Name: media_publicationmedia_asset_id_5ac27e2b; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX media_publicationmedia_asset_id_5ac27e2b ON public.media_publicationmedia USING btree (asset_id);


--
-- Name: media_publicationmedia_publication_id_b52f3143; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX media_publicationmedia_publication_id_b52f3143 ON public.media_publicationmedia USING btree (publication_id);


--
-- Name: publication_author__cbde3b_idx; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX publication_author__cbde3b_idx ON public.publications_publication USING btree (author_id, created_at DESC);


--
-- Name: publication_communi_0c5796_idx; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX publication_communi_0c5796_idx ON public.publications_publication USING btree (community_id, created_at DESC);


--
-- Name: publication_kind_6e88f6_idx; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX publication_kind_6e88f6_idx ON public.publications_publication USING btree (kind, created_at DESC);


--
-- Name: publication_visibil_2e70ec_idx; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX publication_visibil_2e70ec_idx ON public.publications_publication USING btree (visibility, created_at DESC);


--
-- Name: publications_publication_author_id_19724618; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX publications_publication_author_id_19724618 ON public.publications_publication USING btree (author_id);


--
-- Name: publications_publication_community_id_77f620ea; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX publications_publication_community_id_77f620ea ON public.publications_publication USING btree (community_id);


--
-- Name: publications_publication_tags_publication_id_0c0fdb4f; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX publications_publication_tags_publication_id_0c0fdb4f ON public.publications_publication_tags USING btree (publication_id);


--
-- Name: publications_publication_tags_tag_id_80febaf6; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX publications_publication_tags_tag_id_80febaf6 ON public.publications_publication_tags USING btree (tag_id);


--
-- Name: publications_publicationrevision_editor_id_70922eae; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX publications_publicationrevision_editor_id_70922eae ON public.publications_publicationrevision USING btree (editor_id);


--
-- Name: publications_publicationrevision_publication_id_a3963966; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX publications_publicationrevision_publication_id_a3963966 ON public.publications_publicationrevision USING btree (publication_id);


--
-- Name: publications_tag_slug_5702ce16; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX publications_tag_slug_5702ce16 ON public.publications_tag USING btree (slug);


--
-- Name: publications_tag_slug_5702ce16_like; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX publications_tag_slug_5702ce16_like ON public.publications_tag USING btree (slug varchar_pattern_ops);


--
-- Name: publications_tag_slug_ci_unique; Type: INDEX; Schema: public; Owner: forum
--

CREATE UNIQUE INDEX publications_tag_slug_ci_unique ON public.publications_tag USING btree (lower((slug)::text));


--
-- Name: social_comm_communi_2d04e8_idx; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX social_comm_communi_2d04e8_idx ON public.social_communitysubscription USING btree (community_id, created_at DESC);


--
-- Name: social_comm_user_id_917f52_idx; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX social_comm_user_id_917f52_idx ON public.social_communitysubscription USING btree (user_id, created_at DESC);


--
-- Name: social_communitysubscription_community_id_0b240998; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX social_communitysubscription_community_id_0b240998 ON public.social_communitysubscription USING btree (community_id);


--
-- Name: social_communitysubscription_user_id_92aeb596; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX social_communitysubscription_user_id_92aeb596 ON public.social_communitysubscription USING btree (user_id);


--
-- Name: social_user_followe_0bada7_idx; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX social_user_followe_0bada7_idx ON public.social_userfollow USING btree (follower_id, created_at DESC);


--
-- Name: social_user_followi_535fb2_idx; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX social_user_followi_535fb2_idx ON public.social_userfollow USING btree (following_id, created_at DESC);


--
-- Name: social_userfollow_follower_id_10e05253; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX social_userfollow_follower_id_10e05253 ON public.social_userfollow USING btree (follower_id);


--
-- Name: social_userfollow_following_id_8a6da1ca; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX social_userfollow_following_id_8a6da1ca ON public.social_userfollow USING btree (following_id);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: users_email_case_insensitive_unique; Type: INDEX; Schema: public; Owner: forum
--

CREATE UNIQUE INDEX users_email_case_insensitive_unique ON public.users_user USING btree (lower((email)::text));


--
-- Name: users_nickname_case_insensitive_unique; Type: INDEX; Schema: public; Owner: forum
--

CREATE UNIQUE INDEX users_nickname_case_insensitive_unique ON public.users_user USING btree (lower((nickname)::text));


--
-- Name: users_user_email_243f6e77_like; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX users_user_email_243f6e77_like ON public.users_user USING btree (email varchar_pattern_ops);


--
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- Name: users_user_nickname_8ecfd550_like; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX users_user_nickname_8ecfd550_like ON public.users_user USING btree (nickname varchar_pattern_ops);


--
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: forum
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: communities_community communities_community_owner_id_15a7d936_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.communities_community
    ADD CONSTRAINT communities_community_owner_id_15a7d936_fk_users_user_id FOREIGN KEY (owner_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: media_mediaasset media_mediaasset_owner_id_bb8ce699_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.media_mediaasset
    ADD CONSTRAINT media_mediaasset_owner_id_bb8ce699_fk_users_user_id FOREIGN KEY (owner_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: media_publicationmedia media_publicationmed_publication_id_b52f3143_fk_publicati; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.media_publicationmedia
    ADD CONSTRAINT media_publicationmed_publication_id_b52f3143_fk_publicati FOREIGN KEY (publication_id) REFERENCES public.publications_publication(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: media_publicationmedia media_publicationmedia_asset_id_5ac27e2b_fk_media_mediaasset_id; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.media_publicationmedia
    ADD CONSTRAINT media_publicationmedia_asset_id_5ac27e2b_fk_media_mediaasset_id FOREIGN KEY (asset_id) REFERENCES public.media_mediaasset(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: publications_publication publications_publica_community_id_77f620ea_fk_communiti; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.publications_publication
    ADD CONSTRAINT publications_publica_community_id_77f620ea_fk_communiti FOREIGN KEY (community_id) REFERENCES public.communities_community(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: publications_publicationrevision publications_publica_editor_id_70922eae_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.publications_publicationrevision
    ADD CONSTRAINT publications_publica_editor_id_70922eae_fk_users_use FOREIGN KEY (editor_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: publications_publication_tags publications_publica_publication_id_0c0fdb4f_fk_publicati; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.publications_publication_tags
    ADD CONSTRAINT publications_publica_publication_id_0c0fdb4f_fk_publicati FOREIGN KEY (publication_id) REFERENCES public.publications_publication(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: publications_publicationrevision publications_publica_publication_id_a3963966_fk_publicati; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.publications_publicationrevision
    ADD CONSTRAINT publications_publica_publication_id_a3963966_fk_publicati FOREIGN KEY (publication_id) REFERENCES public.publications_publication(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: publications_publication_tags publications_publica_tag_id_80febaf6_fk_publicati; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.publications_publication_tags
    ADD CONSTRAINT publications_publica_tag_id_80febaf6_fk_publicati FOREIGN KEY (tag_id) REFERENCES public.publications_tag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: publications_publication publications_publication_author_id_19724618_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.publications_publication
    ADD CONSTRAINT publications_publication_author_id_19724618_fk_users_user_id FOREIGN KEY (author_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: social_communitysubscription social_communitysubs_community_id_0b240998_fk_communiti; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.social_communitysubscription
    ADD CONSTRAINT social_communitysubs_community_id_0b240998_fk_communiti FOREIGN KEY (community_id) REFERENCES public.communities_community(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: social_communitysubscription social_communitysubscription_user_id_92aeb596_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.social_communitysubscription
    ADD CONSTRAINT social_communitysubscription_user_id_92aeb596_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: social_userfollow social_userfollow_follower_id_10e05253_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.social_userfollow
    ADD CONSTRAINT social_userfollow_follower_id_10e05253_fk_users_user_id FOREIGN KEY (follower_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: social_userfollow social_userfollow_following_id_8a6da1ca_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.social_userfollow
    ADD CONSTRAINT social_userfollow_following_id_8a6da1ca_fk_users_user_id FOREIGN KEY (following_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_users_use FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: forum
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 5FqoMa3iFoTGx20PDSvNKg3vfdL0FmULgyPAGcwGMjiSvfWOGE6QuR3mOmVPEXu

