"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { FormEvent, useState } from "react";
import { UsersRound } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { EmptyState } from "@/components/ui/empty-state";
import { LoadingBlock } from "@/components/ui/loading";
import { clientApi, errorMessage } from "@/lib/client-api";
import type { Community, CursorPage } from "@/lib/types";
import { useAuth } from "@/providers/auth-provider";

export default function CommunitiesPage(){const {user}=useAuth();const qc=useQueryClient();const [open,setOpen]=useState(false);const [name,setName]=useState("");const [slug,setSlug]=useState("");const [description,setDescription]=useState("");const query=useQuery({queryKey:["communities"],queryFn:()=>clientApi<CursorPage<Community>>("/communities/")});const create=useMutation({mutationFn:()=>clientApi<Community>("/communities/",{method:"POST",body:JSON.stringify({name,slug,description})}),onSuccess:()=>{setOpen(false);setName("");setSlug("");setDescription("");qc.invalidateQueries({queryKey:["communities"]})}});function submit(e:FormEvent){e.preventDefault();create.mutate();}
return <AppShell><section className="page-head split-head"><div><div className="eyebrow">СООБЩЕСТВА</div><h1>Пространства по интересам</h1><p>Список формируется только из сообществ, реально созданных в Django.</p></div>{user?<button className="primary-button" onClick={()=>setOpen(v=>!v)}>{open?"Закрыть":"Создать сообщество"}</button>:null}</section>{open?<form className="compact-form panel" onSubmit={submit}><div className="form-grid"><label>Название<input value={name} onChange={e=>setName(e.target.value)} required minLength={3}/></label><label>Slug<input value={slug} onChange={e=>setSlug(e.target.value.toLowerCase().replace(/\s+/g,"-"))} required minLength={3} placeholder="embedded-systems"/></label></div><label>Описание<textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)}/></label>{create.isError?<div className="form-error">{errorMessage(create.error)}</div>:null}<button className="primary-button" disabled={create.isPending}>{create.isPending?"Создаём…":"Создать"}</button></form>:null}{query.isLoading?<LoadingBlock/>:query.data?.results.length?<div className="community-grid">{query.data.results.map(c=><article className="community-card" key={c.id}><div className="community-symbol">#</div><div><h2>{c.name}</h2><div className="meta-row">/{c.slug} • {c.subscriber_count} подписчиков</div><p>{c.description||"Описание пока не добавлено."}</p></div></article>)}</div>:<EmptyState icon={UsersRound} title="Сообществ ещё нет" text={user?"Создайте первое сообщество и задайте направление обсуждениям.":"После регистрации можно будет создать первое сообщество."} action={!user?{href:"/register",label:"Зарегистрироваться"}:undefined}/>}</AppShell>}
