"use client";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { Power,Search } from "lucide-react";
import { useState } from "react";
import { AdminEmpty,StatusBadge } from "@/components/admin/admin-ui";
import { LoadingBlock } from "@/components/ui/loading";
import { clientApi,errorMessage } from "@/lib/client-api";
import type { AdminCommunity,AdminPage } from "@/lib/types";
export default function AdminCommunitiesPage(){const [search,setSearch]=useState("");const qc=useQueryClient();const q=useQuery({queryKey:["admin","communities",search],queryFn:()=>clientApi<AdminPage<AdminCommunity>>(`/admin/communities/?limit=100&q=${encodeURIComponent(search)}`)});const update=useMutation({mutationFn:({id,active}:{id:string;active:boolean})=>clientApi<AdminCommunity>(`/admin/communities/${id}/`,{method:"PATCH",body:JSON.stringify({is_active:active})}),onSuccess:()=>{qc.invalidateQueries({queryKey:["admin","communities"]});qc.invalidateQueries({queryKey:["admin","overview"]});}});return <><div className="admin-page-head"><div><div className="eyebrow">СТРУКТУРА СООБЩЕСТВА</div><h1>Сообщества</h1><p>Управляйте доступностью групп без удаления их публикаций и истории.</p></div></div><div className="admin-toolbar"><div className="admin-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Название, slug или владелец…"/></div></div>{q.isLoading?<LoadingBlock/>:q.error?<div className="error-panel">{errorMessage(q.error)}</div>:!q.data?.results.length?<AdminEmpty title="Сообществ нет" text="Здесь появятся реальные созданные пользователями сообщества."/>:<div className="admin-community-grid">{q.data.results.map(c=><article className="admin-community-card" key={c.id}><div><StatusBadge value={c.is_active?"active":"inactive"}/><h3>{c.name}</h3><span>/{c.slug} · владелец @{c.owner.nickname}</span><p>{c.description||"Описание не заполнено."}</p></div><div className="admin-community-foot"><span><strong>{c.subscriber_count}</strong> подписчиков · <strong>{c.publication_count}</strong> публикаций</span><button className="admin-action-button" disabled={update.isPending} onClick={()=>update.mutate({id:c.id,active:!c.is_active})}><Power size={15}/>{c.is_active?"Отключить":"Включить"}</button></div></article>)}</div>}{update.error?<div className="form-error admin-inline-error">{errorMessage(update.error)}</div>:null}</>}
