"use client";

import { useMutation, useQuery } from "@tanstack/react-query";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { AppShell } from "@/components/layout/app-shell";
import { clientApi, errorMessage } from "@/lib/client-api";
import type { Community, CursorPage, Publication } from "@/lib/types";
import { useAuth } from "@/providers/auth-provider";

export default function NewPublicationPage(){const router=useRouter();const {user,loading}=useAuth();const [type,setType]=useState<"post"|"article"|"topic">("topic");const [title,setTitle]=useState("");const [text,setText]=useState("");const [tags,setTags]=useState("");const [communityId,setCommunityId]=useState("");const communities=useQuery({queryKey:["communities"],queryFn:()=>clientApi<CursorPage<Community>>("/communities/")});const create=useMutation({mutationFn:()=>clientApi<Publication>("/publications/",{method:"POST",body:JSON.stringify({type,title:type==="post"?title:title.trim(),content:[{type:"paragraph",text:text.trim()}],community_id:communityId||null,tags:tags.split(",").map(v=>v.trim()).filter(Boolean)})}),onSuccess:data=>router.push(`/publications/${data.id}`)});if(loading)return <AppShell><div className="loading-block">Проверяем сессию…</div></AppShell>;if(!user)return <AppShell><div className="empty-state"><h2>Нужен аккаунт</h2><p>Создавать публикации могут только зарегистрированные пользователи.</p><button className="primary-button" onClick={()=>router.push("/login")}>Войти</button></div></AppShell>;
function submit(e:FormEvent){e.preventDefault();if(!text.trim())return;create.mutate();}
return <AppShell><section className="page-head"><div><div className="eyebrow">СОЗДАНИЕ</div><h1>Новая публикация</h1><p>Первый реальный контент Night Iris. После публикации он сразу появится в API и публичной ленте.</p></div></section><form className="editor-panel" onSubmit={submit}><div className="type-selector">{(["topic","post","article"] as const).map(value=><button type="button" key={value} onClick={()=>setType(value)} className={type===value?"active":""}>{value==="topic"?"Вопрос":value==="post"?"Пост":"Статья"}</button>)}</div>{type!=="post"?<label>Заголовок<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={300} required placeholder={type==="topic"?"Сформулируйте вопрос":"Название статьи"}/></label>:<label>Короткий заголовок <span className="optional">необязательно</span><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={300}/></label>}<label>Текст<textarea value={text} onChange={e=>setText(e.target.value)} rows={12} required placeholder="Напишите содержимое публикации…"/></label><div className="form-grid"><label>Теги <span className="optional">через запятую</span><input value={tags} onChange={e=>setTags(e.target.value)} placeholder="django, python, backend"/></label><label>Сообщество <span className="optional">необязательно</span><select value={communityId} onChange={e=>setCommunityId(e.target.value)}><option value="">Без сообщества</option>{communities.data?.results.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div>{create.isError?<div className="form-error">{errorMessage(create.error)}</div>:null}<div className="editor-actions"><button type="button" className="secondary-button" onClick={()=>router.back()}>Отмена</button><button className="primary-button" disabled={create.isPending}>{create.isPending?"Публикуем…":"Опубликовать"}</button></div></form></AppShell>}
