# Generated by Django 5.2.17 on 2026-08-10 10:40

import apps.publications.content
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(allow_unicode=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['slug'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='publications_tag_slug_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('post', 'Post'), ('article', 'Article'), ('topic', 'Topic')], max_length=16)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('content', models.JSONField(default=list, validators=[apps.publications.content.validate_content_blocks])),
                ('content_text', models.TextField(blank=True, editable=False)),
                ('visibility', models.CharField(choices=[('published', 'Published'), ('hidden', 'Hidden')], default='published', max_length=16)),
                ('current_revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='communities.community')),
                ('tags', models.ManyToManyField(blank=True, related_name='publications', to='publications.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=300)),
                ('content', models.JSONField(default=list)),
                ('tags_snapshot', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_revisions', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='publications.publication')),
            ],
            options={
                'ordering': ['-revision_number'],
                'constraints': [models.UniqueConstraint(fields=('publication', 'revision_number'), name='publication_unique_revision')],
            },
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['visibility', '-created_at'], name='publication_visibil_2e70ec_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['kind', '-created_at'], name='publication_kind_6e88f6_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['author', '-created_at'], name='publication_author__cbde3b_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['community', '-created_at'], name='publication_communi_0c5796_idx'),
        ),
    ]
