"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Eye, EyeOff, Search } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { AdminEmpty, ReasonDialog, StatusBadge } from "@/components/admin/admin-ui";
import { LoadingBlock } from "@/components/ui/loading";
import { clientApi, errorMessage } from "@/lib/client-api";
import type { AdminComment, AdminPage, AdminPublication } from "@/lib/types";

type Target={kind:"publication"|"comment";id:string;hidden:boolean;label:string}|null;
export default function AdminContentPage(){ const [tab,setTab]=useState<"publications"|"comments">("publications"); const [search,setSearch]=useState(""); const [visibility,setVisibility]=useState(""); const [target,setTarget]=useState<Target>(null); const qc=useQueryClient();
 const pubs=useQuery({queryKey:["admin","publications",search,visibility],queryFn:()=>clientApi<AdminPage<AdminPublication>>(`/admin/publications/?limit=100&q=${encodeURIComponent(search)}&visibility=${visibility}`),enabled:tab==="publications"});
 const comments=useQuery({queryKey:["admin","comments",search,visibility],queryFn:()=>clientApi<AdminPage<AdminComment>>(`/admin/comments/?limit=100&q=${encodeURIComponent(search)}&visibility=${visibility}`),enabled:tab==="comments"});
 const action=useMutation({mutationFn:async({t,reason}:{t:NonNullable<Target>;reason:string})=>{const root=t.kind==="publication"?"publications":"comments";return clientApi(`/moderation/${root}/${t.id}/hidden/`,{method:t.hidden?"DELETE":"PUT",body:JSON.stringify({reason})});},onSuccess:()=>{qc.invalidateQueries({queryKey:["admin",tab]});qc.invalidateQueries({queryKey:["admin","overview"]});qc.invalidateQueries({queryKey:["admin","actions"]});}});
 const loading=tab==="publications"?pubs.isLoading:comments.isLoading; const error=tab==="publications"?pubs.error:comments.error;
 return <><div className="admin-page-head"><div><div className="eyebrow">МОДЕРАЦИЯ КОНТЕНТА</div><h1>Контент</h1><p>Проверяйте публикации и обсуждения. Вместо удаления используется скрытие с причиной и журналом действий.</p></div></div><div className="admin-tabs"><button className={tab==="publications"?"active":""} onClick={()=>setTab("publications")}>Публикации</button><button className={tab==="comments"?"active":""} onClick={()=>setTab("comments")}>Комментарии и ответы</button></div><div className="admin-toolbar"><div className="admin-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Поиск по тексту или автору…"/></div><select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="">Любая видимость</option><option value="published">Опубликовано</option><option value="hidden">Скрыто</option></select></div>
 {loading?<LoadingBlock/>:error?<div className="error-panel">{errorMessage(error)}</div>:tab==="publications"?<PublicationRows items={pubs.data?.results??[]} onAction={setTarget}/>:<CommentRows items={comments.data?.results??[]} onAction={setTarget}/>}<ReasonDialog open={!!target} title={target?.hidden?`Восстановить «${target.label}»?`:`Скрыть «${target?.label}»?`} confirmLabel={target?.hidden?"Восстановить":"Скрыть"} onClose={()=>setTarget(null)} onConfirm={async reason=>{if(target)await action.mutateAsync({t:target,reason});}}/>{action.error?<div className="form-error admin-inline-error">{errorMessage(action.error)}</div>:null}</>;
}
function PublicationRows({items,onAction}:{items:AdminPublication[];onAction:(t:Target)=>void}){if(!items.length)return <AdminEmpty title="Публикаций нет" text="В базе пока нет контента, подходящего под фильтры."/>;return <div className="admin-list">{items.map(p=><article className="admin-content-row" key={p.id}><div className="admin-content-main"><div className="admin-content-meta"><StatusBadge value={p.visibility}/><span>{p.type}</span><span>@{p.author.nickname}</span><span>{new Date(p.created_at).toLocaleString("ru-RU")}</span></div><Link href={`/publications/${p.id}`}><h3>{p.title||"Без заголовка"}</h3></Link><p>{p.excerpt||"Текст отсутствует"}</p><div className="admin-content-stats">{p.comment_count} ответов · {p.report_count} жалоб · ревизия {p.current_revision}</div></div><button className="admin-action-button" onClick={()=>onAction({kind:"publication",id:p.id,hidden:p.visibility==="hidden",label:p.title||"публикацию"})}>{p.visibility==="hidden"?<Eye size={16}/>:<EyeOff size={16}/>} {p.visibility==="hidden"?"Восстановить":"Скрыть"}</button></article>)}</div>}
function CommentRows({items,onAction}:{items:AdminComment[];onAction:(t:Target)=>void}){if(!items.length)return <AdminEmpty title="Комментариев нет" text="В базе пока нет обсуждений, подходящих под фильтры."/>;return <div className="admin-list">{items.map(c=><article className="admin-content-row" key={c.id}><div className="admin-content-main"><div className="admin-content-meta"><StatusBadge value={c.visibility}/><span>{c.kind}</span><span>@{c.author.nickname}</span><span>{new Date(c.created_at).toLocaleString("ru-RU")}</span></div><h3>{c.publication.title||"Публикация без заголовка"}</h3><p>{c.excerpt||"Текст отсутствует"}</p><div className="admin-content-stats">score {c.score} · {c.report_count} жалоб {c.is_accepted?"· принятый ответ":""}</div></div><button className="admin-action-button" onClick={()=>onAction({kind:"comment",id:c.id,hidden:c.visibility==="hidden",label:c.excerpt.slice(0,45)||"комментарий"})}>{c.visibility==="hidden"?<Eye size={16}/>:<EyeOff size={16}/>} {c.visibility==="hidden"?"Восстановить":"Скрыть"}</button></article>)}</div>}
