"use client";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { Check, Search, X } from "lucide-react";
import { useState } from "react";
import { AdminEmpty, StatusBadge } from "@/components/admin/admin-ui";
import { LoadingBlock } from "@/components/ui/loading";
import { clientApi,errorMessage } from "@/lib/client-api";
import type { AdminPage,AdminReport } from "@/lib/types";

export default function AdminReportsPage(){const [status,setStatus]=useState("open");const [editing,setEditing]=useState<AdminReport|null>(null);const [note,setNote]=useState("");const qc=useQueryClient();const q=useQuery({queryKey:["admin","reports",status],queryFn:()=>clientApi<AdminPage<AdminReport>>(`/admin/reports/?limit=100&status=${status}`)});const update=useMutation({mutationFn:({id,s,note}:{id:string;s:string;note:string})=>clientApi<AdminReport>(`/admin/reports/${id}/`,{method:"PATCH",body:JSON.stringify({status:s,resolution_note:note})}),onSuccess:()=>{setEditing(null);setNote("");qc.invalidateQueries({queryKey:["admin","reports"]});qc.invalidateQueries({queryKey:["admin","overview"]});}});
 return <><div className="admin-page-head"><div><div className="eyebrow">ОЧЕРЕДЬ МОДЕРАЦИИ</div><h1>Жалобы</h1><p>Сначала переведите неоднозначную жалобу в «на проверке», затем разрешите или отклоните её с заметкой.</p></div></div><div className="admin-toolbar"><div className="admin-filter-label"><Search size={14}/>Статус очереди</div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="open">Открытые</option><option value="reviewing">На проверке</option><option value="resolved">Разрешённые</option><option value="dismissed">Отклонённые</option><option value="">Все</option></select></div>{q.isLoading?<LoadingBlock/>:q.error?<div className="error-panel">{errorMessage(q.error)}</div>:!q.data?.results.length?<AdminEmpty title="Очередь пуста" text="Жалоб с выбранным статусом сейчас нет."/>:<div className="admin-report-grid">{q.data.results.map(r=><article className="admin-report" key={r.id}><div className="admin-report-top"><StatusBadge value={r.status}/><span>{r.target_type}</span><time>{new Date(r.created_at).toLocaleString("ru-RU")}</time></div><h3>{r.target_label}</h3><div className="admin-report-reason">{r.reason}</div><p>{r.details||"Пользователь не добавил пояснение."}</p><div className="admin-report-footer"><span>от <strong>@{r.reporter.nickname}</strong></span><button className="secondary-button compact-button" onClick={()=>{setEditing(r);setNote(r.resolution_note||"")}}>Обработать</button></div></article>)}</div>}
 {editing?<div className="admin-modal-backdrop" onMouseDown={()=>setEditing(null)}><div className="admin-modal" onMouseDown={e=>e.stopPropagation()}><button className="admin-modal-close" onClick={()=>setEditing(null)}><X size={17}/></button><div className="eyebrow">ЖАЛОБА</div><h2>{editing.target_label}</h2><p className="admin-modal-copy">Причина: <strong>{editing.reason}</strong><br/>{editing.details||"Без пояснения"}</p><label>Заметка модератора<textarea rows={5} value={note} onChange={e=>setNote(e.target.value)} placeholder="Что было проверено и почему принято это решение?"/></label><div className="admin-resolution-actions"><button onClick={()=>update.mutate({id:editing.id,s:"reviewing",note})}>На проверку</button><button className="good" onClick={()=>update.mutate({id:editing.id,s:"resolved",note})}><Check size={15}/> Разрешить</button><button className="bad" onClick={()=>update.mutate({id:editing.id,s:"dismissed",note})}>Отклонить</button></div></div></div>:null}{update.error?<div className="form-error admin-inline-error">{errorMessage(update.error)}</div>:null}</>}
