"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, ArrowLeft, CheckCheck, MessageCircle, MoreHorizontal, Paperclip, Plus, Send, UsersRound, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { AppShell } from "@/components/layout/app-shell";
import { ConversationAvatar } from "@/components/messenger/conversation-avatar";
import { MessageBubble } from "@/components/messenger/message-bubble";
import { NewChatPanel } from "@/components/messenger/new-chat-panel";
import { EmptyState } from "@/components/ui/empty-state";
import { LoadingBlock } from "@/components/ui/loading";
import { clientApi, errorMessage } from "@/lib/client-api";
import { uploadMediaFile } from "@/lib/media-upload";
import type { MediaAsset, MessengerConversation, MessengerMessage, MessengerMessagesPage, MessengerSocketEvent } from "@/lib/types";
import { useMessengerSocket } from "@/hooks/use-messenger-socket";
import { useAuth } from "@/providers/auth-provider";

export function MessengerShell({ initialConversationId }: { initialConversationId?:string }) {
  const {user,loading}=useAuth(); const router=useRouter(); const qc=useQueryClient(); const [newChat,setNewChat]=useState(false); const [text,setText]=useState(""); const [reply,setReply]=useState<MessengerMessage|null>(null); const [attachments,setAttachments]=useState<MediaAsset[]>([]); const [uploading,setUploading]=useState<number|null>(null); const [typing,setTyping]=useState<Record<string,string>>({}); const typingTimer=useRef<ReturnType<typeof setTimeout>|null>(null); const endRef=useRef<HTMLDivElement|null>(null);
  const conversations=useQuery({queryKey:["messenger-conversations"],queryFn:()=>clientApi<MessengerConversation[]>("/messenger/conversations/"),enabled:Boolean(user),refetchInterval:30000});
  const selectedId=initialConversationId || conversations.data?.[0]?.id;
  const selected=conversations.data?.find(c=>c.id===selectedId);
  const messages=useQuery({queryKey:["messenger-messages",selectedId],queryFn:()=>clientApi<MessengerMessagesPage>(`/messenger/conversations/${selectedId}/messages/?limit=80`),enabled:Boolean(user&&selectedId)});
  const handleEvent=(event:MessengerSocketEvent)=>{if(event.type==="typing"&&event.conversation_id&&event.user_id!==user?.id){setTyping(v=>({...v,[event.conversation_id!]:event.active?event.nickname||"печатает…":""}));return;} if(event.type==="presence"||event.type.startsWith("message.")||event.type.startsWith("conversation.")){qc.invalidateQueries({queryKey:["messenger-conversations"]});qc.invalidateQueries({queryKey:["messenger-unread"]});if(event.conversation_id)qc.invalidateQueries({queryKey:["messenger-messages",event.conversation_id]});}};
  const {connected,sendTyping}=useMessengerSocket(handleEvent,Boolean(user));
  const send=useMutation({mutationFn:()=>clientApi<MessengerMessage>(`/messenger/conversations/${selectedId}/messages/`,{method:"POST",body:JSON.stringify({client_id:crypto.randomUUID(),text,reply_to_id:reply?.id||null,attachment_ids:attachments.map(a=>a.id)})}),onSuccess:()=>{setText("");setReply(null);setAttachments([]);qc.invalidateQueries({queryKey:["messenger-messages",selectedId]});qc.invalidateQueries({queryKey:["messenger-conversations"]});}});
  const read=useMutation({mutationFn:(messageId?:string)=>clientApi(`/messenger/conversations/${selectedId}/read/`,{method:"POST",body:JSON.stringify({message_id:messageId||null})}),onSuccess:()=>{qc.invalidateQueries({queryKey:["messenger-conversations"]});qc.invalidateQueries({queryKey:["messenger-unread"]});}});
  const edit=useMutation({mutationFn:({message,text}:{message:MessengerMessage;text:string})=>clientApi(`/messenger/messages/${message.id}/`,{method:"PATCH",body:JSON.stringify({text})})});
  const remove=useMutation({mutationFn:(message:MessengerMessage)=>clientApi(`/messenger/messages/${message.id}/`,{method:"DELETE"})});
  const react=useMutation({mutationFn:({message,emoji}:{message:MessengerMessage;emoji:string})=>clientApi(`/messenger/messages/${message.id}/reaction/`,{method:"PUT",body:JSON.stringify({emoji})})});
  useEffect(()=>{const last=messages.data?.results.at(-1);if(last&&selectedId)read.mutate(last.id);endRef.current?.scrollIntoView({behavior:"smooth"});},[messages.data?.results.length,selectedId]);
  if(!loading&&!user)return <AppShell><EmptyState icon={MessageCircle} title="Мессенджер доступен после входа" text="Личные и групповые чаты Night Iris синхронизируются через общий API и WebSocket." action={{href:"/login",label:"Войти"}}/></AppShell>;
  if(!user)return <AppShell><LoadingBlock/></AppShell>;
  const onType=(value:string)=>{setText(value);if(!selectedId)return;sendTyping(selectedId,true);if(typingTimer.current)clearTimeout(typingTimer.current);typingTimer.current=setTimeout(()=>sendTyping(selectedId,false),1200)};
  const upload=async(file:File)=>{setUploading(0);try{const asset=await uploadMediaFile(file,p=>setUploading(p.percent));setAttachments(v=>[...v,asset]);}finally{setUploading(null)}};
  return <AppShell><section className="messenger-layout">
    <aside className={`messenger-sidebar ${initialConversationId?"mobile-chat-open":""}`}><div className="messenger-title"><div><div className="eyebrow">NIGHT IRIS / REALTIME</div><h1>Сообщения</h1></div><button className="primary-icon-button" onClick={()=>setNewChat(true)}><Plus size={18}/></button></div><div className="messenger-connection"><span className={connected?"online":""}/>{connected?"Realtime подключён":"Переподключение…"}</div>{newChat?<NewChatPanel onClose={()=>setNewChat(false)} onCreated={c=>{setNewChat(false);qc.invalidateQueries({queryKey:["messenger-conversations"]});router.push(`/messages/${c.id}`)}}/>:<div className="conversation-list">{conversations.isLoading?<LoadingBlock/>:conversations.data?.length?conversations.data.map(c=><Link href={`/messages/${c.id}`} key={c.id} className={`conversation-row ${selectedId===c.id?"active":""}`}><ConversationAvatar conversation={c} me={user} size="sm"/><span className="conversation-copy"><strong>{c.display_title}</strong><small>{c.last_message?`${c.last_message.sender_id===user.id?"Вы: ":""}${c.last_message.text}`:"Чат создан"}</small></span><span className="conversation-meta"><time>{c.last_message_at?new Date(c.last_message_at).toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"}):""}</time>{c.unread_count?<b>{c.unread_count>99?"99+":c.unread_count}</b>:null}</span></Link>):<div className="messenger-empty-list"><MessageCircle/><strong>Здесь пока тихо</strong><span>Начните личный чат или создайте группу.</span><button onClick={()=>setNewChat(true)}>Новый чат</button></div>}</div>}</aside>
    <main className={`messenger-chat ${selected?"has-chat":""}`}>{selected?<><header className="chat-header"><Link href="/messages" className="mobile-chat-back"><ArrowLeft size={17}/></Link><ConversationAvatar conversation={selected} me={user} size="sm"/><div><strong>{selected.display_title}</strong><span>{typing[selected.id]|| (selected.kind==="direct"?(selected.members.find(m=>m.user.id!==user.id)?.online?"в сети":"Night Iris"):`${selected.members.length} участников`)}</span></div><button className="icon-button"><MoreHorizontal size={17}/></button></header><div className="message-scroll">{messages.isLoading?<LoadingBlock/>:messages.data?.results.map((m,i)=>{const prev=messages.data!.results[i-1];const grouped=Boolean(prev&&prev.sender.id===m.sender.id&&new Date(m.created_at).getTime()-new Date(prev.created_at).getTime()<5*60*1000);return <MessageBubble key={m.id} message={m} me={user} grouped={grouped} onReply={setReply} onEdit={message=>{const value=window.prompt("Изменить сообщение",message.text);if(value!==null)edit.mutate({message,text:value})}} onDelete={message=>{if(window.confirm("Удалить сообщение для всех участников?"))remove.mutate(message)}} onReact={(message,emoji)=>react.mutate({message,emoji})}/>})}<div ref={endRef}/></div><footer className="chat-composer">{reply?<div className="composer-reply"><ReplyIcon/><span><strong>@{reply.sender.nickname}</strong>{reply.text||"Вложение"}</span><button onClick={()=>setReply(null)}><X size={13}/></button></div>:null}{attachments.length?<div className="composer-attachments">{attachments.map(a=><span key={a.id}>{a.kind==="image"?"🖼":"📎"} {a.original_name||a.name}<button onClick={()=>setAttachments(v=>v.filter(x=>x.id!==a.id))}><X size={10}/></button></span>)}</div>:null}<div className="composer-row"><label className="composer-attach"><Paperclip size={18}/>{uploading!==null?<b>{uploading}%</b>:null}<input type="file" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.currentTarget.value=""}}/></label><textarea rows={1} value={text} onChange={e=>onType(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();if((text.trim()||attachments.length)&&!send.isPending)send.mutate()}}} placeholder="Сообщение…"/><button className="composer-send" disabled={(!text.trim()&&!attachments.length)||send.isPending} onClick={()=>send.mutate()}><Send size={17}/></button></div>{send.error?<div className="composer-error">{errorMessage(send.error)}</div>:null}</footer></>:<div className="messenger-chat-empty"><div className="messenger-empty-mark"><MessageCircle size={34}/></div><h2>Night Iris Messenger</h2><p>Выберите диалог слева или создайте новый. Сообщения хранятся в PostgreSQL, а изменения приходят через WebSocket.</p><button className="primary-button" onClick={()=>setNewChat(true)}><Plus size={15}/>Новый чат</button></div>}</main>
  </section></AppShell>;
}
function ReplyIcon(){return <span className="composer-reply-icon">↩</span>}
