"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { AuthShell } from "@/components/auth/auth-shell";
import { ApiError, errorMessage } from "@/lib/client-api";
import { useAuth } from "@/providers/auth-provider";

const initial = { nickname:"", email:"", password:"", password2:"", first_name:"", last_name:"", country:"", nationality:"", interface_language:"ru" };
export default function RegisterPage(){const router=useRouter();const {refresh}=useAuth();const [form,setForm]=useState(initial);const [error,setError]=useState("");const [busy,setBusy]=useState(false);function field(name:keyof typeof initial,value:string){setForm(v=>({...v,[name]:value}));}async function submit(e:FormEvent){e.preventDefault();setError("");if(form.password!==form.password2){setError("Пароли не совпадают.");return;}setBusy(true);try{const {password2,...rest}=form;const body={...rest,country:form.country.toUpperCase(),nationality:form.nationality.toUpperCase()};const r=await fetch("/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const payload=await r.json().catch(()=>null);if(!r.ok)throw new ApiError(r.status,payload);await refresh();router.replace("/profile/edit");}catch(err){setError(errorMessage(err));}finally{setBusy(false);}}
return <AuthShell title="Создать аккаунт" subtitle="После регистрации вы сразу попадёте в настройку социального профиля." footer={<>Уже есть аккаунт? <Link href="/login">Войти</Link></>}><form className="form-stack" onSubmit={submit}><div className="form-grid"><label>Имя<input value={form.first_name} onChange={e=>field("first_name",e.target.value)} required/></label><label>Фамилия<input value={form.last_name} onChange={e=>field("last_name",e.target.value)} required/></label></div><label>Никнейм<input value={form.nickname} onChange={e=>field("nickname",e.target.value)} minLength={3} maxLength={32} autoComplete="username" required/><small>Никнейм используется для входа и публичного @username.</small></label><label>Email<input type="email" value={form.email} onChange={e=>field("email",e.target.value)} autoComplete="email" required/></label><div className="form-grid"><label>Пароль<input type="password" value={form.password} onChange={e=>field("password",e.target.value)} autoComplete="new-password" required/></label><label>Повторите пароль<input type="password" value={form.password2} onChange={e=>field("password2",e.target.value)} autoComplete="new-password" required/></label></div><small className="form-help">Пароль проходит стандартные проверки безопасности Django.</small><div className="form-grid"><label>Страна <small>ISO-2</small><input value={form.country} onChange={e=>field("country",e.target.value.slice(0,2))} placeholder="RU" minLength={2} maxLength={2} required/></label><label>Национальность <small>ISO-2</small><input value={form.nationality} onChange={e=>field("nationality",e.target.value.slice(0,2))} placeholder="RU" minLength={2} maxLength={2} required/></label></div>{error?<div className="form-error">{error}</div>:null}<button className="primary-button wide-button" disabled={busy}>{busy?"Создаём…":"Зарегистрироваться"}</button></form></AuthShell>}
